spring:
  profiles:
    active: oauth
  application:
    name: explore

server:
  port: 8081

reddit:
  client-id: lfq1WrlB7K4tlg
  client-secret: dPX1x5Uos6JvgSFh6mvcW1uyG8c
  username: redditube_explore
  password: 98578652
  type: user

#logging.level:
#  org.springframework.cloud.gateway: TRACE
#  org.springframework.security: TRACE
#  org.springframework.security.oauth2.server.resource: TRACE
#  org.springframework.security.oauth2.core: TRACE
#  org.springframework.web: TRACE
#  org.springframework.security.oauh2: TRACE