spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      routes:
        - id: "ExploreUsers"
          uri: "http://localhost:8081"
          predicates:
            - Path=/u/**
          filters:
            - StripPrefix=1
        #        - name: CircuitBreaker
        #            args:
        #              name: fallback
        #              fallbackUri: forward:/fallback
        - id: "Feed"
          uri: "http://localhost:8082"
          predicates:
            - Path=/feed
          filters:
            - PrefixPath=/subscriptions
        - id: "Subscriptions"
          uri: "http://localhost:8082"
          predicates:
            - Path=/subscriptions
      default-filters:
        - RemoveRequestHeader=Cookie
        - TokenRelay