spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 999s # TODO Find a solution for reddit api delay
      routes:
        - id: "ExploreUsers"
          uri: http://${redditube.services.explorer-users.host}:${redditube.services.explorer-users.port}
          predicates:
            - Path=/u/**
          filters:
            - StripPrefix=1
        #        - name: CircuitBreaker
        #            args:
        #              name: fallback
        #              fallbackUri: forward:/fallback
        - id: "Feed"
          uri: http://${redditube.services.media-posts.host}:${redditube.services.media-posts.port}
          predicates:
            - Path=/feed
          filters:
            - PrefixPath=/subscriptions
        - id: "Subscriptions"
          uri: http://${redditube.services.media-posts.host}:${redditube.services.media-posts.port}
          predicates:
            - Path=/subscriptions
      default-filters:
        - RemoveRequestHeader=Cookie
        - TokenRelay