DROP TYPE IF EXISTS SUBSCRIBABLE_TYPE;
CREATE TYPE SUBSCRIBABLE_TYPE AS ENUM ('USER', 'SUBREDDIT');
CREATE TABLE IF NOT EXISTS SUBSCRIBABLE
(
    ID   VARCHAR,
    TYPE SUBSCRIBABLE_TYPE
);

ALTER TABLE SUBSCRIBABLE
    ADD CONSTRAINT SUBSCRIBABLE_PK PRIMARY KEY (ID, TYPE);

COMMENT ON TABLE SUBSCRIBABLE IS 'Represents an entity you can subscribe to';

CREATE TABLE IF NOT EXISTS SUBSCRIPTION
(
    USERNAME        VARCHAR,
    SUBSCRIBABLE_ID VARCHAR,
    SUBSCRIBABLE_TYPE SUBSCRIBABLE_TYPE
);

ALTER TABLE SUBSCRIPTION
    ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY (USERNAME, SUBSCRIBABLE_ID),
    ADD CONSTRAINT SUBSCRIPTION_SUBSCRIBABLE_FK FOREIGN KEY (SUBSCRIBABLE_ID, SUBSCRIBABLE_TYPE) REFERENCES SUBSCRIBABLE (ID, TYPE);

COMMENT ON TABLE SUBSCRIPTION IS 'Subscription between a user and a subscribable';
