CREATE TABLE IF NOT EXISTS SUBSCRIBABLE
(
    ID      SERIAL,
    HANDLE  VARCHAR,
    TYPE    VARCHAR
);

ALTER TABLE SUBSCRIBABLE
    ADD CONSTRAINT SUBSCRIBABLE_PK PRIMARY KEY (ID),
    ADD CONSTRAINT SUBSCRIBABLE_TYPE_ENUM CHECK (TYPE IN ('USER', 'SUBREDDIT')),
    ADD CONSTRAINT SUBSCRIBABLE_UNIQUE_HANDLE_TYPE UNIQUE (HANDLE, TYPE);

COMMENT ON TABLE SUBSCRIBABLE IS 'Represents an entity you can subscribe to';

CREATE TABLE IF NOT EXISTS SUBSCRIPTION
(
    ID              SERIAL,
    USERNAME        VARCHAR,
    SUBSCRIBABLE_ID INT
);

ALTER TABLE SUBSCRIPTION
    ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY (ID),
    ADD CONSTRAINT SUBSCRIPTION_SUBSCRIBABLE_FK FOREIGN KEY (SUBSCRIBABLE_ID) REFERENCES SUBSCRIBABLE (ID),
    ADD CONSTRAINT SUBSCRIPTION_UNIQUE_USERNAME_SUBSCRIBABLE_ID UNIQUE (USERNAME, SUBSCRIBABLE_ID);

COMMENT ON TABLE SUBSCRIPTION IS 'Subscription between a user and a subscribable';
