CREATE TABLE IF NOT EXISTS REDDITUBE_USER
(
	USERNAME VARCHAR,
    EMAIL VARCHAR,
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	IDP_ID VARCHAR
);

ALTER TABLE REDDITUBE_USER
    ADD CONSTRAINT USER_PK PRIMARY KEY(USERNAME),
    ADD CONSTRAINT USER_EMAIL_UNIQUE UNIQUE(EMAIL);

COMMENT ON TABLE REDDITUBE_USER IS 'User of the application';