CREATE TABLE IF NOT EXISTS REDDITUBE_USER
(
	ID UUID DEFAULT UUID_GENERATE_V4(),
    EMAIL VARCHAR,
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR
);

ALTER TABLE REDDITUBE_USER
    ADD CONSTRAINT USER_PK PRIMARY KEY(ID),
    ADD CONSTRAINT USER_EMAIL_UNIQUE UNIQUE(EMAIL);

COMMENT ON TABLE REDDITUBE_USER IS 'User of the application';