CREATE TABLE "redditube_user"
(
	ID UUID DEFAULT UUID_GENERATE_V4(),
    EMAIL VARCHAR,
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR
);

ALTER TABLE "redditube_user" ADD CONSTRAINT USER_PK PRIMARY KEY(ID);
ALTER TABLE "redditube_user" ADD CONSTRAINT USER_EMAIL_UNIQUE UNIQUE(EMAIL);

COMMENT ON TABLE "redditube_user" IS 'User of the application';