CREATE TYPE SUBSCRIBABLE_TYPE AS ENUM ('USER', 'SUBREDDIT');
CREATE TABLE IF NOT EXISTS SUBSCRIBABLE
(
    ID   SERIAL,
    TYPE SUBSCRIBABLE_TYPE
);

ALTER TABLE SUBSCRIBABLE
    ADD CONSTRAINT SUBSCRIBABLE_PK PRIMARY KEY (ID);

COMMENT ON TABLE SUBSCRIBABLE IS 'Represents an entity you can subscribe to';

CREATE TABLE IF NOT EXISTS SUBSCRIPTION
(
    ID              SERIAL,
    USER_ID         UUID,
    SUBSCRIBABLE_ID INT
);

ALTER TABLE SUBSCRIPTION
    ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY (ID),
    ADD CONSTRAINT SUBSCRIPTION_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES REDDITUBE_USER (ID),
    ADD CONSTRAINT SUBSCRIPTION_SUBSCRIBABLE_ID_FK FOREIGN KEY (SUBSCRIBABLE_ID) REFERENCES SUBSCRIBABLE (ID);

COMMENT ON TABLE SUBSCRIPTION IS 'Subscription between a user and a subscribable';
