spring:
  main:
    banner-mode: off
  liquibase:
    change-log: classpath:liquibase/changelog.xml

# Disable Spring Security default password logging
logging:
  level:
    org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration: off

redditube:
  hosts:
    explorer: http://localhost:8081
    mediaposts: http://localhost:8082