spring:
  profiles:
    active: oauth
  application:
    name: mediaposts
  datasource:
    username: postgres
    password: 98578652
    url: jdbc:postgresql://localhost:5432/redditube
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: ScraperTaskScheduler

server:
  port: 8082

redditube:
  scraper:
    restart-period: PT15M # 15 Minutes
  minio:
    endpoint: http://localhost:9000
    access-key: minio
    secret-key: 98578652

