version: "3.8"
services:
  dex:
    build: ./dex
    ports:
      - "5556:5556"
    volumes:
      - ./dex/config:/opt/dex/config
    depends_on:
      - postgres
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - ~/dev/mount:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '98578652'
      POSTGRES_MULTIPLE_DATABASES: dex,redditube
      PGDATA: /var/lib/postgresql/data/pgdata